### ISSUE TITLE
Portal does not check if exit portal is in a scene tree

### ISSUE THREAD

**Issue by TurqW** [Donitzo/godot-simple-portal-system#3]
SUPER helpful example, thank you for creating it!

Quick nitpick: currently, if the exit portal is orphaned (due to user error with dynamic creation, etc), the viewport will remain enabled, and Godot will respond to all the "global_transform" calls with `Transform3D.IDENTITY`. So the portal will still attempt to render, but will just show whatever's at the origin.

N.B. Godot doesn't check "is_inside_tree()" as part of "is_visible_in_tree()", it only checks whether the node has any ancestors marked as not visible.

While this is definitely a PEBKAC/"well then don't let that happen, dummy" case, the current behavior is not the easiest to debug, and this could be changed with one extra check here: https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal.gd#L65 or here: https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal.gd#L121

**Comment by Donitzo** [comment]
Thank you for the feedback.

That's a good suggestion and I have implemented it in the portal class. I also added a check for if the portal belongs to the correct SceneTree during raytracing. I guess it would technically be possible to have multiple scenes with portals if for example using ViewPorts with their own worlds.
