### ISSUE TITLE
Portal facing another portal

### ISSUE THREAD

**Issue by Gus-The-Forklift-Driver** [Donitzo/godot-simple-portal-system#5]
I have a simple scene with a portal (A-B) looking towards another portal (C-D).
When looking at C through A-B the portal is not visible:
(me)---A      B----C <not visible
I've tried to change the process priority based on the distance from the camera but no changes.
I've also setup a test env with a camera looking at a mesh with a viewport texture and it works properly. 
I don't really know what else to try.
Any ideas would help.

PS : it's a very cool project :)

**Comment by Donitzo** [comment]
Hello!

That would be an example of a recursive portal. The issue with that is that portal CD have to be viewed from the perspective of AB. It means there must be a way to update the portal logic for CD based on the player camera as seen through AB. It is quite confusing and I'm not entirely sure how to do it in godot. Like, how do you know in which order to draw the portals? By distance from player? That doesn't work. But if you happen to have some idea how to implement it I'd happily add it.

**Comment by Gus-The-Forklift-Driver** [comment]
Maybe a visibility hashmap, witch portal can see witch portals. Then build a visibility tree of the portals in view of the player and render the leaf portals (the ones at the end of the tree). This would allow for reclusive portals.
But might be complicated to force godot to render the viewports in the right order ?

For the camera position it's the "virtual player" position of the previous portal.

For computing the visibility a ray cast might be a simple start.

For building the visibily tree, the player could send a signal to all visible portal who would then propagate a signal to portals visible by it (direction matters in this case portal A to portal B isnt the same as portal B to A) once the signal reaches a leaf node we have the order.

But all this is just me rambling, I have very little idea of how to implement all this.

**Comment by Donitzo** [comment]
Yeah you're right. You'd have to change the draw order of portals, and maybe even add update logic in the middle of a draw call, which I'm not entire sure how to do without a custom rendering pipeline.

The original non-recursive portal works as fairly basic example how to use portals which isn't overly complicated, but maybe implementing recursive portals in a separate branch could be a good idea.

**Comment by Gus-The-Forklift-Driver** [comment]
Yeah I understand that it's out of the scope of this project.
