### ISSUE TITLE
portal teleportation on wrong axis

### ISSUE THREAD

**Issue by Lebweuh** [Donitzo/godot-simple-portal-system#6]
first of all thank you for this magnificent portals. i have a small issue and that is portal teleporting on wrong axis. when i enter portal 1 it teleports me to exit portal as expected but my axis stays the same. i have tested this on demo project and got same results too. for visual explaination i attached an image

![resim](https://github.com/user-attachments/assets/c50c100f-c65a-4e96-956d-ef4e9e1239d5)

**Comment by Donitzo** [comment]
Hello! Since the portals change the global transform, it should work fine in rotating the player. Are you accidentally overriding the player rotation globally? How do you normally look around?

**Comment by Lebweuh** [comment]
my player is a characterbody3d and i calculate and add velocity to make it move. the problem is like in the image attached when the player enter portal on X+ axis they exit at X+ axis too instead they should face exit portal facing direction so we dont have to place portals  at 180° and -180° always like letters like "qp" or "db". i dont think velocity is the problem but it doesnt turn the player properly. run your portal demo and place one portal 90­­° to see for yourself

![resim](https://github.com/user-attachments/assets/edecb2cb-4891-4d25-aa6d-6e11be406b32)
![resim](https://github.com/user-attachments/assets/fefad06f-95f8-4f87-8724-6bf1cd003e5c)

**Comment by Donitzo** [comment]
In the portal demo, you have to comment out these two lines to see how it works, otherwise the rotation will just be reset the next frame:

```
#rotation_degrees = Vector3(0, _mouse_look.x, 0)
#_camera.rotation_degrees = Vector3(_mouse_look.y, 0, 0)
```

and also remove this which I had accidentally left behind:

```
        if abs(position.z) > 7.1:
            position.z -= 7.1 * 2 * sign(position.z)
```

**Comment by Lebweuh** [comment]
yeah i figured out that the problem is the demo is translating the player instead of actually moving it and this makes the bug unnoticable on demo. this means our demo player is not affected by gravity or any physics. when i enter the portal at low velocity everything is normal but when i enter at high velocity i get launched into the axis i entered.

![resim](https://github.com/user-attachments/assets/9f562c5a-b8ed-4d21-879d-786d1a36de9d)

like in the attached image if i go like 50km/h without releasing the forward button that bug happens i get rotated alright but my velocity direction is the same. if a player tries to create a game inspired by the game portal they will definetly encounter this problem. i have been trying to find a workaround for and only solution found is place portals 180 and -180 still searching for more useable solution any help will be appreciated thank you

**Comment by Donitzo** [comment]
I updated the teleport to handle RigidBody3D velocity changes as well. Try it and see if it helps:

[https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal_teleport.gd](https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal_teleport.gd)

![physics_boxes](https://github.com/user-attachments/assets/156262cc-3322-41a3-a3eb-228b4e5a2a43)

**Comment by Lebweuh** [comment]
yeah kind of working? and you definetly should add a cooldown mechanism or that sort of thing because like in the attachment the box is teleporting back and forth endlessly until cycle breaks.
https://github.com/user-attachments/assets/2986f290-1707-4725-8f1c-b50ff5b11af8
and i tried to disable the teleportation and enable it 1 second later to make a very basic cooldown mechanisim and it didnt seemed to work either maybe you update the your demo scene file so i can see what i did wrong i am sure collisionshapes or aread3D's are on right place. the rigidbody velocity bug seemed to be fixed with few minor bugs just need to make sure it is going at right velocity and right position but i meant mainly for characterbody3D because nearly all projects use characterbody to "move_and_slide()" to make their fps controllers including me. in my opinion both rigid and characterbody should be supported by teleportation script so users can teleport players with correct velocity or throw grenades at portals sort of thing. currently in my characterbody3D mentioned bug still occours it doesnt teleport me at right velocity. these are my suggestions to make it better thanks.

**Comment by Donitzo** [comment]
I split the teleports into two files to keep one simple:

[https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/simple_portal_teleport.gd](https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/simple_portal_teleport.gd)

[https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal_teleport.gd](https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal_teleport.gd)

In the second one, I changed the velocity constraint so that it works for any type of node. Now it should not teleport things not heading towards the portal.

How does the CharacterBody3D movement act when it teleports? It doesn't expose the velocity vector I think to modify.

**Comment by Lebweuh** [comment]
here is the video demonstrates it.

https://github.com/user-attachments/assets/79e8234b-0fbd-4aef-b47f-ea96ff80fcbb





![resim](https://github.com/user-attachments/assets/42979b7f-d349-46c1-833f-aaedabb5cba8)
![resim](https://github.com/user-attachments/assets/67df359e-d95c-48ec-ac6d-f4a74e3f03a2)


this was the bug i am talking about from start. still occours with your new teleportation script but it seems to fixed rigidbody3D though but it is going wrong direction too:

https://github.com/user-attachments/assets/e2a27b7a-13cf-4cf0-b598-f129777d45cc


since i didnt write the code i dont know what would cause this issue but my assumption is the rotation of the portals i have a feeling that portals should have more strict rotation or scaling rules to make it work best or should the script be more dynamic? i dont know these are just suggestions.

.
.




also while writing this comment i encountered the in this comments first mentioned bug's another consequence and here is the video and image for it:

https://github.com/user-attachments/assets/b90952a7-fd5f-4901-bbd7-688c3726c777


the main cause for this is the same as the bug i mentioned first in this comment and that is the velocity bug and lack of cooldown. the cooldown seems an easy fix but i dont think velocity will be easy or not. here is an image that demonstrates it better:
![resim](https://github.com/user-attachments/assets/90435a47-cef2-4c7b-b3e0-926d268d4142)
![resim](https://github.com/user-attachments/assets/e724cf25-0423-4122-a57d-45f9af859dab)


the portals indeed would work perfectly for any horror or dungeon game but any fast paced playthroughs like portal 2 or splitgate these portals wont work with them.

**Comment by Donitzo** [comment]
I updated the [portal teleport](https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/portal_teleport.gd) script again to specifically handle the character body controller as well. It at least seems to work, otherwise you should re-check the portal orientations. You can increase the push velocity for the teleporters to push out objects from the portals so they don't get stuck.

![tank](https://github.com/user-attachments/assets/9d59d09a-7750-43c1-bad2-74487dfe97fa)

**Comment by Lebweuh** [comment]
the problem got solved when two portals look at same direction or opposite direction (180,-180 or 0,0 degrees) the portal works perfectly

https://github.com/user-attachments/assets/35331148-4b48-4cf8-bdf7-14f0e28c4384

https://github.com/user-attachments/assets/35c3fd2d-19ae-4366-8ad3-1fd269793f28


but this still has one small problem i dont knw why would cause this issue? when the portals placed at 90 and 0 degrees this happens and the push velocity doesnt seem to help either:





https://github.com/user-attachments/assets/88802748-7741-43e4-8715-ae37ffe54226


https://github.com/user-attachments/assets/737742bc-9921-45ee-8faa-906905832898


![resim](https://github.com/user-attachments/assets/664353ed-5ade-45b3-824a-bc054bc78117)


i tried to disable the portal after first entry and this is the result


https://github.com/user-attachments/assets/3783d099-075d-4d4a-99f3-cf18abac38fb

![resim](https://github.com/user-attachments/assets/7532ba47-ea2d-4885-b0e0-2b09c9c3f8da)


currently this is the final bug i have encountered and every other thing are perfect enough. thanks for your patience i really appreciate it. there are currently two working portal projects ive seen so far for godot 4 and this one is the best among of them because ease of setup and being so dynamic and customizeable keep up the good work

**Comment by Donitzo** [comment]
Thank you.

I made a small update to the portal teleport script to prevent it from teleporting stationary objects. Maybe it should prevent teleporting the player when its standing still.

Edit: I also added support for handling a portal clone object, by specifying a "portal_clone" nodepath as well as the "teleportable_root" path. The clone will only be visible while the node is overlapping the portal.

![clone](https://github.com/user-attachments/assets/5bcdc5cb-e131-4914-82c6-6fbe2e046c4a)

Also renamed the portal_teleport.gd script to [https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/advanced_portal_teleport.gd](https://github.com/Donitzo/godot-simple-portal-system/blob/main/src/scripts/advanced_portal_teleport.gd)

**Comment by Lebweuh** [comment]
yep that bug got fixed and we got "cooldown" effect like i suggsted before it is great now the player wont teleport back to entry portal on exit. my solution was adding a 0.5 second cooldown each entry but this is better. now there is this issue:

https://github.com/user-attachments/assets/7d362ba6-a4ae-475f-a740-88227c45831d


https://github.com/user-attachments/assets/2e7309f0-84a4-42bd-a57e-dbc97dc95869

first attachment is when i disable the portal on first entry for debug purposes as you can see if i place one portal at 90° and other one 0° it launches me to that direction and other attachment is without disabling the portal at first entry it just resets my velocity to 0

![resim](https://github.com/user-attachments/assets/a721ee8d-e6c3-4152-9959-c3ac18670f17)
![resim](https://github.com/user-attachments/assets/43b8d034-72c3-4348-bb43-75b270ce20c9)
first image is disabling the portal area3D on entry for debug so we can see which direction our player goes and second one is untouched your teleportation script and it stops me on exit.
.
.
![resim](https://github.com/user-attachments/assets/cdafb43b-a840-47aa-8270-590da4e14572)
this image represents exit direction of the exit portal and the exit portal is now 45°. the red arrow is where player gets pushed and blue one is where it should push the player instead of red. currently portals work perfectly for 0° and 180°, 0° and 0° or we can do 45° and -45° etc... in other words they can look each other or they can look away from each other they work seamlessly but when their rotation dont match there is this bug begins. i hope i explained it clearly thanks.

**Comment by Donitzo** [comment]
I'm still unable to re-produce the bug. It's like the portals are oriented incorrectly or the player control code is acting strange. Can you provide a minimal runnable example of the bug?

**Comment by Lebweuh** [comment]
https://github.com/Lebweuh/portaltest

i have added you to this repo can you check this out? i tried to 1:1 replicate my own project but it seems still has bugs that i mentioned before dont know why but i now think it is because how people code their controller i took that demo project fps controller from "rbarongr" on github mine was very comlex to implement that easily for a demo project. i think i did everything that you mentioned in README.md if you define some rules for portal transforms i will be happy to follow it.
![resim](https://github.com/user-attachments/assets/0f9a5b9a-5a95-4628-94b1-47eb047518fd)
and also are you sure about this? shouldnt portal teleport monitor instead of the player?

**Comment by Donitzo** [comment]
Yeah I think it should be the other way around.

The issue in your code is that the velocity is overridden each frame, If you add damping you can see it:

```
func _physics_process(delta: float) -> void:
    if mouse_captured: _handle_joypad_camera_rotation(delta)
    var t:float = 1 - pow(0.5, delta)
    velocity = velocity * (1 - t) + (_walk(delta) + _gravity(delta) + _jump(delta)) * t
    move_and_slide()
```

**Comment by Donitzo** [comment]
I notice that there was an issue transforming the velocity using basis. I updated the code to instead transform the direction. The linear velocity should transform correctly now, although I'm not entirely sure if the angular velocity is correct.

**Comment by Lebweuh** [comment]
can you believe it i was going to mention that bug i got the video and ready to post it and before i send the comment you already fixed it.

before:

https://github.com/user-attachments/assets/66bfb761-3527-4cdd-b738-67bbee34e71c


after:

https://github.com/user-attachments/assets/f5106742-59d3-4965-a4b6-1c5a71c300a6

and appearently this commit fixed all of the bugs mentioned in this issue like velocity, direction, rigidbodies and characterbodies. there is still one more minor bug that needs to get looked on but i think the fix relies on how will dev handle the fps controller but i want you to give an advice how would you handle this?:

https://github.com/user-attachments/assets/a60a6d6f-a22a-4053-b5e0-f0caadcfe5e8

![resim](https://github.com/user-attachments/assets/3a41e788-6d1b-4d75-8cad-9659e900d0d4)

when you give portals a rotation it rotates the characterbody also and the camera rotation gets messed up. when writing a controller you give 89 and -89 degrees max and min to prevent the player my solution was lerp the body rotation to 0,0,0 but it doesnt seem look good. we already get the "main_camera" on portals export variables so i think we can do something about it on teleportation script. 
and also as you mentioned it i definetly should add dampening to my velocities i am jut getting into this physics thing recently and this is good to know my other non portal issues should get fixed with it.

**Comment by Donitzo** [comment]
It is rather difficult to try to do some trickery here to make it exit the portal the right way up. In that case I believe the easiest thing to do is to add a function which automatically tries to make the character controller upright again (or whichever direction you are currently considering to be "up"). It's basically just lerping its current orientation so that it tries to be upright again. So that when you go through a portal, your character slowly rises back up to a standing position. The difficult part I guess is trying to make it so that the camera doesn't swing around at the same time.

**Comment by Lebweuh** [comment]
what if we face the camera to direction instead of whole characterbody? like keeping characterbody transform at 0,0,0 all times and changing rotation of the camera using look_at() function or something? would it work?
